import { createClient } from 'npm:@supabase/supabase-js@2'
import webpush from 'npm:web-push@3.6.7'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!, SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, VAPID_PUBLIC_KEY=Deno.env.get('VAPID_PUBLIC_KEY')!, VAPID_PRIVATE_KEY=Deno.env.get('VAPID_PRIVATE_KEY')!, CRON_SECRET=Deno.env.get('CRON_SECRET')!
webpush.setVapidDetails('mailto:admin@example.com',VAPID_PUBLIC_KEY,VAPID_PRIVATE_KEY)
const db=createClient(SUPABASE_URL,SERVICE_ROLE_KEY)
const TZ='Asia/Jakarta'
function zonedParts(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(parts.filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
function toUtc(date:string,time:string){return new Date(`${date}T${time.slice(0,8)}+07:00`)}
Deno.serve(async req=>{if(req.headers.get('x-cron-secret')!==CRON_SECRET)return new Response('Unauthorized',{status:401});try{const now=new Date(),from=new Date(now.getTime()-5*60e3),to=new Date(now.getTime()+26*60*60e3);const {data:apps,error}=await db.from('appointments').select('*').gte('appointment_date',zonedParts(from).year+'-'+zonedParts(from).month+'-'+zonedParts(from).day).lte('appointment_date',zonedParts(to).year+'-'+zonedParts(to).month+'-'+zonedParts(to).day);if(error)throw error;let sent=0;for(const a of apps||[]){const when=toUtc(a.appointment_date,a.appointment_time);for(const [type,ms,title] of [['h1',86400000,'Jadwal Makeup Besok'],['h3',10800000,'Jadwal Makeup 3 Jam Lagi']] as const){const due=new Date(when.getTime()-ms);if(due>=from&&due<=to){const {data:existing}=await db.from('reminders_sent').select('id').eq('appointment_id',a.id).eq('reminder_type',type).maybeSingle();if(existing)continue;const {data:subs}=await db.from('push_subscriptions').select('*').eq('user_id',a.user_id);let any=false;for(const s of subs||[]){try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify({title:`🔔 ${title}`,body:`${a.client_name}\n💄 ${a.event_type}\n📍 ${a.city}\n⏰ ${a.appointment_time.slice(0,5)}`,data:{url:'/'}}));any=true}catch(e){console.error('push failed',e);if(e.statusCode===404||e.statusCode===410)await db.from('push_subscriptions').delete().eq('id',s.id)}}if(any){await db.from('reminders_sent').insert({appointment_id:a.id,reminder_type:type});sent++}}}}return Response.json({ok:true,sent})}catch(e){console.error(e);return Response.json({ok:false,error:String(e)},{status:500})}})
